project_id = "phbehenczyryrlxmgjju"

[functions.send-insights-report]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-billing-history]
verify_jwt = false

[functions.change-subscription]
verify_jwt = false

[functions.send-billing-notification]
verify_jwt = false

[functions.remove-user-access]
verify_jwt = false

[functions.terminate-account]
verify_jwt = false

[functions.auth-rate-limit]
verify_jwt = false
